package autodb

import "jjyz/base/db/migrate"

var Tables = []*migrate.TableConf{
	{
		Name:    "main_city_robot_data",
		Comment: "主线机器人",
		Fields: []*migrate.ColumnConf{
			{Name: "id", Type: "bigint", Comment: "ID", AutoIncrement: true},
			{Name: "robotSeriesId", Type: "bigint", Comment: "主线机器人ID"},
			{Name: "data", Type: "blob", Comment: "主线机器人的数据"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "id"},
			{Type: "uni", Name: "robotSeriesId"},
		},
	},
	{
		Name:    "ask_help",
		Comment: "玩家道具求助",
		Fields: []*migrate.ColumnConf{
			{Name: "player_id", Type: "bigint", Comment: "角色Id"},
			{Name: "data", Type: "blob", Comment: "求助数据"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "uni", Name: "player_id"},
		},
	},
	{
		Name:    "rush_rank",
		Comment: "冲榜达人",
		Fields: []*migrate.ColumnConf{
			{Name: "rank_type", Type: "int", Comment: "冲榜类型"},
			{Name: "data", Type: "blob", Comment: "冲榜数据"},
		},
	},
	{
		Name:    "actor_robot",
		Comment: "角色机器人",
		Fields: []*migrate.ColumnConf{
			{Name: "id", Type: "bigint", Comment: "角色id", AutoIncrement: true},
			{Name: "pf_id", Type: "int", Comment: "平台id", Size: 64},
			{Name: "server_id", Type: "int", Comment: "服务器id", Size: 64},
			{Name: "actor_id", Type: "bigint", Comment: "角色id"},
			{Name: "config_type", Type: "int", Comment: "机器人配置来源,1.竞技场系统机默认器人,2.镜像创建"},
			{Name: "config_id", Type: "bigint", Comment: "配置id"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "id"},
		},
	},
	{
		Name:    "account",
		Comment: "账号表",
		Fields: []*migrate.ColumnConf{
			{Name: "user_id", Type: "int", Comment: "用户唯一ID", Unsigned: true},
			{Name: "account_name", Type: "varchar", Comment: "用户帐户的字符串", Size: 64},
			{Name: "passwd", Type: "varchar", Comment: "玩家的密码", Size: 32},
			{Name: "updatetime", Type: "datetime", Comment: "上次登陆时间"},
			{Name: "pwtime", Type: "bigint", Comment: "密码的有效时间，使用的是unix的时间戳，这里记录的是密码创建的时间"},
			{Name: "gmlevel", Type: "int", Comment: "玩家的GM等级，普通玩家是0.GM等级越高表示权限越高。1-10级GM"},
			{Name: "isinvite", Type: "int", Comment: "是否被邀请创角的号"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "user_id"},
			{Type: "uni", Name: "account_name"},
		},
	},
	{
		Name:    "actors",
		Comment: "玩家的角色表",
		Fields: []*migrate.ColumnConf{
			{Name: "actor_id", Type: "bigint", Comment: "角色id", AutoIncrement: true},
			{Name: "user_id", Type: "int", Comment: "账户ID", Unsigned: true},
			{Name: "actor_name", Type: "varchar", Comment: "玩家名字", Size: 32},
			{Name: "account_name", Type: "varchar", Comment: "账户的名字", Size: 80},
			{Name: "vip", Type: "int", Comment: "vip等级"},
			{Name: "sex", Type: "int", Comment: "性别"},
			{Name: "job", Type: "int", Comment: "职业"},
			{Name: "level", Type: "int", Comment: "等级"},
			{Name: "circle", Type: "int", Comment: "转生等级"},
			{Name: "status", Type: "int", Comment: "0位:已删除,1位:有效,2位:首选 3位:个人重名需补发邮件 4位:帮派重名需补发邮件", Default: "2"},
			{Name: "lastloginip", Type: "bigint", Comment: "上次登录的ip"},
			{Name: "lastlogintime", Type: "datetime", Comment: "角色最后登录时间"},
			{Name: "last_logout_time", Type: "int", Comment: "角色最后登出时间"},
			{Name: "create_time", Type: "datetime", Comment: "角色的创建时间"},
			{Name: "update_time", Type: "datetime", Comment: "服务器的存盘时间，在这个点最后一次更新db"},
			{Name: "yuan_bao", Type: "int", Comment: "元宝"},
			{Name: "bind_diamonds", Type: "int", Comment: "绑定钻石"},
			{Name: "diamonds", Type: "int", Comment: "钻石"},
			{Name: "fight_value", Type: "bigint", Comment: "战力"},
			{Name: "online_flag", Type: "tinyint", Comment: "在线状态"},
			{Name: "recovery_time", Type: "int", Comment: "角色删除时间"},
			{Name: "ban_time", Type: "int", Comment: "封禁角色时间戳"},
			{Name: "ditch_id", Type: "int", Comment: "渠道id"},
			{Name: "sub_ditch_id", Type: "int", Comment: "子渠道id"},
			{Name: "logined_days", Type: "int", Comment: "登陆天数"},
			{Name: "day_online_time", Type: "int", Comment: "每日在线时间"},
			{Name: "new_day_reset_time", Type: "int", Comment: "上一次跨天的时间戳"},
			{Name: "exp", Type: "bigint", Comment: "玩家经验"},
			{Name: "appear_info", Type: "blob", Comment: "玩家的外观信息"},
			{Name: "fairy_stone", Type: "int", Comment: "灵石"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "actor_id"},
			{Type: "mul", Name: "user_id"},
			{Type: "mul", Name: "actor_name"},
			{Type: "mul", Name: "account_name"},
		},
	},
	{
		Name:    "actor_binary_data",
		Comment: "角色二进制数据",
		Fields: []*migrate.ColumnConf{
			{Name: "actor_id", Type: "bigint", Comment: "角色id"},
			{Name: "binary_data", Type: "blob", Comment: "玩家数据"},
			{Name: "binary_pb3_data", Type: "blob", Comment: "玩家pb3数据"},
			{Name: "medium_binary_pb3_data", Type: "mediumblob", Comment: "玩家pb3数据(mediumblob)"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "actor_id"},
		},
	},
	{
		Name:    "constvariables",
		Comment: "常量表",
		Fields: []*migrate.ColumnConf{
			{Name: "actorid_series_bits", Type: "int", Comment: "玩家序列号所占bits，需要同时修改以下掩码"},
			{Name: "actorid_series_mask", Type: "bigint", Comment: "玩家序列号掩码"},
			{Name: "actor_mail_max", Type: "int", Comment: "玩家邮件数量达到最大值后开始替换旧邮件"},
		},
	},
	{
		Name:    "gmcmd",
		Comment: "gm命令表",
		Fields: []*migrate.ColumnConf{
			{Name: "id", Type: "bigint", Comment: "索引", AutoIncrement: true},
			{Name: "deltime", Type: "int", Comment: "删除时间，0表示未被读取"},
			{Name: "exectime", Type: "int", Comment: "指令执行时间"},
			{Name: "cmd", Type: "varchar", Comment: "命令名称", Size: 256},
			{Name: "param1", Type: "varchar", Comment: "参数1", Size: 256, Default: "null"},
			{Name: "param2", Type: "varchar", Comment: "参数2", Size: 256, Default: "null"},
			{Name: "param3", Type: "varchar", Comment: "参数3", Size: 256, Default: "null"},
			{Name: "param4", Type: "varchar", Comment: "参数4", Size: 256, Default: "null"},
			{Name: "param5", Type: "varchar", Comment: "参数5", Size: 256, Default: "null"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "id"},
		},
	},
	{
		Name:    "actormail",
		Comment: "邮件系统",
		Fields: []*migrate.ColumnConf{
			{Name: "mail_id", Type: "bigint", Comment: "邮件ID"},
			{Name: "actor_id", Type: "bigint", Comment: "邮件主人的ID"},
			{Name: "conf_id", Type: "int", Comment: "邮件配表id"},
			{Name: "type", Type: "int", Comment: "邮件的类型"},
			{Name: "status", Type: "int", Comment: "邮件的状态"},
			{Name: "send_tick", Type: "int", Comment: "发信时间"},
			{Name: "send_name", Type: "varchar", Comment: "发信人名字", Size: 32},
			{Name: "title", Type: "varchar", Comment: "标题", Size: 48},
			{Name: "content", Type: "varchar", Comment: "邮件内容", Size: 1024},
			{Name: "award_str", Type: "varchar", Comment: "奖励", Size: 512, Default: "null"},
			{Name: "user_item", Type: "blob", Comment: "user_item"},
			{Name: "mail_date", Type: "datetime", Comment: "数据库时间"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "mail_id"},
			{Type: "mul", Name: "actor_id"},
		},
	},
	{
		Name:    "server_mail",
		Comment: "群发邮件",
		Fields: []*migrate.ColumnConf{
			{Name: "id", Type: "bigint", Unsigned: true, Comment: "索引", AutoIncrement: true},
			{Name: "conf_id", Type: "int", Comment: "邮件配表id"},
			{Name: "type", Type: "int", Comment: "邮件的类型"},
			{Name: "send_tick", Type: "int", Unsigned: true, Comment: "发信的unix时间"},
			{Name: "title", Type: "varchar", Comment: "邮件标题", Size: 128},
			{Name: "content", Type: "varchar", Comment: "邮件内容", Size: 1024},
			{Name: "award_str", Type: "varchar", Comment: "奖励", Size: 512},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "id"},
		},
	},
	{
		Name:    "actorservermail",
		Comment: "玩家上次领取的群发邮件记录",
		Fields: []*migrate.ColumnConf{
			{Name: "actor_id", Type: "bigint", Comment: "角色ID"},
			{Name: "mail_id", Type: "int", Comment: "上次领取到的群发邮件索引"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "actor_id"},
		},
	},
	{
		Name:    "itempool",
		Comment: "道具表",
		Fields: []*migrate.ColumnConf{
			{Name: "id", Type: "bigint", Comment: "自增id", AutoIncrement: true},
			{Name: "actor_id", Type: "bigint", Comment: "玩家ID"},
			{Name: "sys_id", Type: "tinyint", Comment: "所属系统ID"},
			{Name: "item_guid", Type: "bigint", Comment: "物品的Guid是"},
			{Name: "conf_id", Type: "int", Comment: "物品的ID"},
			{Name: "count", Type: "smallint", Comment: "物品的数量"},
			{Name: "bind", Type: "tinyint", Comment: "物品是否绑定"},
			{Name: "time", Type: "int", Comment: "物品的过期时间"},
			{Name: "pos", Type: "int", Comment: "穿戴部位"},
			{Name: "rand_attr", Type: "blob", Comment: "随机属性"},
			{Name: "lucky", Type: "int", Comment: "角色索引"},
			{Name: "union1", Type: "int", Comment: "联合字段"},
			{Name: "drop_info", Type: "blob", Comment: "掉落信息"},
			{Name: "rand_attr2", Type: "blob", Comment: "随机属性2"},
			{Name: "union2", Type: "int", Comment: "联合字段2"},
			{Name: "ext", Type: "blob", Comment: "扩展信息"},
			{Name: "md5", Type: "varchar", Size: 255, Comment: "hash", Default: ""},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "id"},
			{Type: "mul", Name: "actor_id"},
		},
	},
	{
		Name:    "skill",
		Comment: "玩家的技能表",
		Fields: []*migrate.ColumnConf{
			{Name: "actor_id", Type: "bigint", Comment: "玩家ID"},
			{Name: "skill_id", Type: "int", Comment: "技能ID"},
			{Name: "level", Type: "int", Comment: "技能等级"},
			{Name: "cd_time", Type: "int", Comment: "CD时间"},
			{Name: "cd", Type: "bigint", Comment: "CD时间2"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "mul", Name: "actor_id"},
		},
	},
	{
		Name:    "offlinedata",
		Comment: "玩家的离线数据，只在起服时load，关服时save",
		Fields: []*migrate.ColumnConf{
			{Name: "actor_id", Type: "bigint", Comment: "角色ID"},
			{Name: "sys_id", Type: "int", Comment: "系统ID"},
			{Name: "data", Type: "mediumblob", Comment: "数据"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "actor_id"},
			{Type: "pri", Name: "sys_id"},
		},
	},
	{
		Name:    "guildlist",
		Comment: "公会列表",
		Fields: []*migrate.ColumnConf{
			{Name: "guild_id", Type: "bigint", Comment: "公会id"},
			{Name: "srv_id", Type: "int", Comment: "服务器ID,合服也要维持合服前数据，否则序列号会出问题"},
			{Name: "name", Type: "varchar", Size: 64, Comment: "公会名"},
			{Name: "level", Type: "smallint", Comment: "公会等级"},
			{Name: "leader_id", Type: "bigint", Comment: "会长id"},
			{Name: "leader_name", Type: "varchar", Size: 64, Comment: "会长名"},
			{Name: "leader_boundary_lv", Type: "int", Comment: "会长境界等级"},
			{Name: "apply_level", Type: "smallint", Comment: "申请等级限制"},
			{Name: "apply_power", Type: "int", Comment: "申请战力限制"},
			{Name: "approval_mode", Type: "tinyint", Comment: "审批模式"},
			{Name: "notice", Type: "varchar", Size: 128, Default: "null", Comment: "行会公告"},
			{Name: "binary_data", Type: "blob", Comment: "公会二进制数据"},
			{Name: "money", Type: "int", Comment: "公会资金"},
			{Name: "creat_time", Type: "int", Comment: "创建时间"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "guild_id"},
		},
	},
	{
		Name:    "guildmember",
		Comment: "公会成员",
		Fields: []*migrate.ColumnConf{
			{Name: "guild_id", Type: "bigint", Comment: "公会id"},
			{Name: "srv_id", Type: "int", Comment: "服务器ID"},
			{Name: "actor_id", Type: "bigint", Comment: "玩家id"},
			{Name: "position", Type: "int", Comment: "职位"},
			{Name: "donate", Type: "int", Comment: "贡献值"},
			{Name: "join_time", Type: "int", Comment: "加入时间"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "mul", Name: "guild_id"},
			{Type: "pri", Name: "actor_id"},
		},
	},
	{
		Name:    "friends",
		Comment: "好友数据",
		Fields: []*migrate.ColumnConf{
			{Name: "actor_id", Type: "bigint", Comment: "玩家id"},
			{Name: "friend_id", Type: "bigint", Comment: "好友id"},
			{Name: "f_type", Type: "int", Comment: "好友类型"},
			{Name: "intimacy", Type: "int", Comment: "亲密度"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "mul", Name: "actor_id"},
		},
	},
	{
		Name:    "actormsg",
		Comment: "角色的消息表",
		Fields: []*migrate.ColumnConf{
			{Name: "msg_id", Type: "bigint", Comment: "信息id", AutoIncrement: true},
			{Name: "actor_id", Type: "bigint", Comment: "消息对应的角色id，表示这个消息要发送的对象"},
			{Name: "msg_type", Type: "int", Comment: "消息的类型"},
			{Name: "msg", Type: "tinyblob", Comment: "消息的内容，二进制数据"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "msg_id"},
			{Type: "pri", Name: "actor_id"},
		},
	},
	{
		Name:    "rank",
		Comment: "排行榜数据",
		Fields: []*migrate.ColumnConf{
			{Name: "rank_type", Type: "int", Comment: "排行榜类型"},
			{Name: "rank_data", Type: "mediumblob", Comment: "排行榜数据"},
		},
	},
	{
		Name:    "serverinfo",
		Comment: "服务器信息",
		Fields: []*migrate.ColumnConf{
			{Name: "server_id", Type: "int", Comment: "服务器id", Unsigned: true},
			{Name: "forbid_create_flag", Type: "int", Comment: "禁止创角标记", Unsigned: true},
			{Name: "open_time", Type: "int", Comment: "开服时间戳", Unsigned: true},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "server_id"},
		},
	},
	{
		Name:    "globalvar",
		Comment: "一些杂七杂八数据",
		Fields: []*migrate.ColumnConf{
			{Name: "server_id", Type: "int", Comment: "服务器id", Unsigned: true},
			{Name: "binary_data", Type: "mediumblob", Comment: "数据"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "server_id"},
		},
	},
	{
		Name:    "charge",
		Comment: "充值",
		Fields: []*migrate.ColumnConf{
			{Name: "id", Type: "bigint", Comment: "自增id", AutoIncrement: true},
			{Name: "account_id", Type: "bigint", Comment: "账号id"},
			{Name: "actor_id", Type: "bigint", Comment: "玩家id"},
			{Name: "charge_id", Type: "int", Unsigned: true, Comment: "充值id"},
			{Name: "cash_num", Type: "int", Unsigned: true, Comment: "金额"},
			{Name: "check_time", Type: "int", Comment: "检测时间"},
			{Name: "insert_time", Type: "int", Comment: "入库时间"},
			{Name: "pay_no", Type: "varchar", Comment: "渠道订单号", Size: 64},
			{Name: "cp_no", Type: "varchar", Comment: "我们订单号", Size: 64},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "id"},
		},
	},
	{
		Name:    "guilddepot",
		Comment: "仙盟仓库",
		Fields: []*migrate.ColumnConf{
			{Name: "id", Type: "bigint", Comment: "自增id", AutoIncrement: true},
			{Name: "guild_id", Type: "bigint", Comment: "帮派ID"},
			{Name: "srv_id", Type: "int", Comment: "服务器ID"},
			{Name: "sys_id", Type: "tinyint", Comment: "所属系统ID"},
			{Name: "conf_id", Type: "int", Comment: "物品的ID"},
			{Name: "count", Type: "smallint", Comment: "物品的数量"},
			{Name: "bind", Type: "tinyint", Comment: "物品是否绑定"},
			{Name: "time", Type: "int", Comment: "物品的过期时间"},
			{Name: "pos", Type: "int", Comment: "穿戴部位"},
			{Name: "rand_attr", Type: "blob", Comment: "随机属性"},
			{Name: "union1", Type: "int", Comment: "联合字段"},
			{Name: "rand_attr2", Type: "blob", Comment: "随机属性2"},
			{Name: "union2", Type: "int", Comment: "联合字段2"},
			{Name: "ext", Type: "blob", Comment: "扩展信息"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "id"},
			{Type: "mul", Name: "guild_id"},
		},
	},
	{
		Name:    "actor_statics",
		Comment: "玩家统计数据",
		Fields: []*migrate.ColumnConf{
			{Name: "id", Type: "int", Comment: "自增id", AutoIncrement: true},
			{Name: "actor_id", Type: "bigint", Comment: "玩家id"},
			{Name: "quest_id", Type: "int", Unsigned: true, Comment: "已完成的主线任务id"},
			{Name: "scene_id", Type: "int", Unsigned: true, Comment: "最后所在场景id"},
			{Name: "charge_diamond", Type: "bigint", Comment: "累计充值钻石数"},
			{Name: "last_charge_time", Type: "int", Unsigned: true, Comment: "最后充值时间"},
			{Name: "jy_timestamp", Type: "int", Unsigned: true, Comment: "禁言结束时间戳"},
			{Name: "use_charge_item", Type: "tinyint", Comment: "是否使用充值道具"},
			{Name: "device", Type: "varchar", Size: 64, Comment: "设备信息", Default: "'unknown'"},
			{Name: "online_minutes", Type: "int", Unsigned: true, Comment: "在线时长(分钟)"},
			{Name: "jing_jie_lv", Type: "int", Unsigned: true, Comment: "境界(层)"},
			{Name: "all_equip_strong_lv", Type: "int", Unsigned: true, Comment: "装备强化总等级"},
			{Name: "all_accessory_strong_lv", Type: "int", Unsigned: true, Comment: "饰品强化总等级"},
			{Name: "destined_fa_bao_lv", Type: "int", Unsigned: true, Comment: "本命法宝等级"},
			{Name: "meridians_total_lv", Type: "int", Unsigned: true, Comment: "经脉等级"},
			{Name: "mage_body_lv", Type: "int", Unsigned: true, Comment: "炼体等级"},
			{Name: "fairy_wing_lv", Type: "int", Unsigned: true, Comment: "仙翼等级"},
			{Name: "fairy_master_train_lv", Type: "int", Unsigned: true, Comment: "仙尊试炼进度"},
			{Name: "rider_lv", Type: "int", Unsigned: true, Comment: "坐骑等级"},
			{Name: "four_symbols_dragon", Type: "int", Unsigned: true, Comment: "青龙等级"},
			{Name: "four_symbols_tiger", Type: "int", Unsigned: true, Comment: "白虎等级"},
			{Name: "four_symbols_rose_finch", Type: "int", Unsigned: true, Comment: "朱雀等级"},
			{Name: "four_symbols_tortoise", Type: "int", Unsigned: true, Comment: "玄武等级"},
			{Name: "nirvana_lv", Type: "int", Unsigned: true, Comment: "转生"},
			{Name: "nirvana_sub_lv", Type: "int", Unsigned: true, Comment: "转生子等级"},
			{Name: "charge_tokens", Type: "int", Unsigned: true, Comment: "充值代币数量"},
			{Name: "history_charge_tokens", Type: "bigint", Unsigned: true, Comment: "历史充值代币数量"},
			{Name: "ditch_tokens", Type: "int", Unsigned: true, Comment: "渠道仙票数量"},
			{Name: "history_ditch_tokens", Type: "bigint", Unsigned: true, Comment: "历史渠道仙票数量"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "id"},
			{Type: "mul", Name: "actor_id"},
		},
	},
	{
		Name:    "actor_series",
		Comment: "角色id序列号",
		Fields: []*migrate.ColumnConf{
			{Name: "id", Type: "int", Comment: "自增id", AutoIncrement: true},
			{Name: "server_id", Type: "int", Comment: "服务器id", Unsigned: true},
			{Name: "series", Type: "int", Comment: "序列号", Unsigned: true},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "id"},
		},
	},
	{
		Name:    "online_data",
		Comment: "玩家在线数据",
		Fields: []*migrate.ColumnConf{
			{Name: "player_id", Type: "bigint", Comment: "角色Id"},
			{Name: "data", Type: "blob", Comment: "在线数据"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "uni", Name: "player_id"},
		},
	},
	{
		Name:    "yy_cmd_setting",
		Comment: "运营活动预设",
		Fields: []*migrate.ColumnConf{
			{Name: "id", Type: "bigint", Comment: "预设id"},
			{Name: "yy_id", Type: "int", Comment: "运营活动id"},
			{Name: "start_time", Type: "int", Comment: "开启时间"},
			{Name: "end_time", Type: "int", Comment: "结束时间"},
			{Name: "status", Type: "int", Comment: "状态"},
			{Name: "conf_idx", Type: "int", Comment: "运行配置"},
			{Name: "ext", Type: "varchar", Comment: "后台穿透参数", Size: 64},
			{Name: "open_time", Type: "int", Comment: "实际开启日"},
		},
		Keys: []*migrate.ColumnKeySt{
			{Type: "pri", Name: "id"},
		},
	},
}
